algorithm_kwargs:
  batch_size:                     512
  max_path_length:                3000
  min_num_steps_before_training:  10000
  num_epochs:                     250
  num_eval_paths_per_epoch:       10
  num_expl_steps_per_train_loop:  1000
  num_trains_per_train_loop:      1000

eval_env_num:                     10
expl_env_num:                     10
layer_size:                       64
structureDNN:                     [64, 64]
replay_buffer_size:               1000000

trainer_kwargs:
  discount:                       0.9777
  alpha:                          0.2
  policy_lr:                      0.001 #0.00044
  qf_lr:                          0.001 #0.00044
  use_automatic_entropy_tuning:   true
  polyak_step:                    0.005
  target_update_period:           1
  lambda_t:                       400
  lambda_s:                       400

version:                          attitude
mode:                             nominal
aspiration:                       eval
near_stall:                       false

trimmed:                          True
agent:
  n_hidden:                       2
  n_hidden_units:                 64

training:
  t_max:                          80.0
  terrain_penalty:                2
  c:                              [1, 1, 1]

pitch_ref:
  block_w:                        10.0
  smooth_w:                       6.0
  amplitude:                      20.0
  n_levels:                       15
  var_w:                          0.1
  zero_start:                     false

roll_ref:
  block_w:                        8.0
  smooth_w:                       4.0
  amplitude:                      35.0
  n_levels:                       15
  var_w:                          0.1
  zero_start:                     false

pitch_ref_e:
  p_sw:                           7.0
  p_sp:                           [20, 10, 0, -15, 0]
  p_sp_t:                         [0, 16, 36, 56, 70]

pitch_ref_elq:
  p_sw:                           7.0
  p_sp:                           [15, 5, -5, -15, 0]
  p_sp_t:                         [0, 16, 36, 56, 70]

pitch_ref_stall:
  p_sw:                           7.0
  p_sp:                           [0, 20, 40, 15, 0]
  p_sp_t:                         [0, 10, 35, 55, 70]

roll_ref_e:
  r_sw:                           4.0
  r_sp:                           [30, 0, -30, 0, 30, 0, -30]
  r_sp_t:                         [8, 18, 28, 38, 48, 58, 68]

roll_ref_elq:
  r_sw:                           4.0
  r_sp:                           [30, 0, -30, 0, 30, 0, -30]
  r_sp_t:                         [8, 18, 28, 38, 48, 58, 68]
